apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-worker
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: spark-2.1.0-bin-hadoop2.6 
        imagePullPolicy : "IfNotPresent"
        name: spark-worker
        ports:
        - containerPort: 7078
          protocol: TCP
        resources :
          requests :
            cpu : 1
            memory : "512Mi"
          limits :
             cpu : 4
             memory : "3Gi"

        command:
         - "/bin/bash"
         - "-c"
         - "--"
        args :
                - '. ./start-common.sh ; /opt/spark/sbin/start-slave.sh spark://spark-master:7077 -c 4 -m 2G ; sleep infinity'
